 function create_file_UM(fname,lon,lat,time)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%       Create reprocess of UM data
%        
%       fname  :   name of the UM file
%       lon    :   grid point in longitude
%       lat    :   grid point in latitude
%       time   :   julian day from 1960. 01.01. 00:00
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nw = netcdf(fname, 'clobber');

disp('  ')
disp(['file        :       ',fname])

%  Create dimensions
% nw('x') = length(x);
% nw('y') = length(y);
% nw('time') = length(time);

[LN LM] =  size(lon);
nw('x') = LM ;
nw('y') = LN ;
nw('time') = length(time);

%
%  Create variables and attributes
%

nw.description =  'Merged the UM data';
nw.author = ' Created by C-S. KIM ';
nw.date = date;

VarName = 'latitude';
nw{VarName} = ncfloat('y', 'x');
nw{VarName}.units = 'degrees_north';
nw{VarName}.long_name = 'latitude';
nw{VarName}(:) = lat;

VarName = 'longitude';
nw{VarName} = ncfloat('y', 'x');
nw{VarName}.units = 'degrees_east';
nw{VarName}.long_name = 'longitude';
nw{VarName}(:) = lon;

VarName = 'time';
nw{VarName} = ncdouble('time');
nw{VarName}.units = 'seconds since 1970-01-01 00:00:00.0 0:00';
nw{VarName}.long_name = 'verification time generated by wgrib2 function verftime()';

VarName = 'ugrd';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'UGRD_10maboveground; U-Component of Wind';
nw{VarName}.units = 'm/s';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'vgrd';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'VGRD_10maboveground; V-Component of Wind';
nw{VarName}.units = 'm/s';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'tmp2m';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'Temperature_2maboveground';
nw{VarName}.units = 'K';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'rh2m';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'Relative Humidity_2maboveground';
nw{VarName}.units = '%';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'dpt2m';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'Dew Point Temperature_2maboveground';
nw{VarName}.units = 'K';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'press';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'PRES_surface';
nw{VarName}.units = 'Pa';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'nswrs';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'NSWRS_surface; Net Short-Wave Radiation Flux at Surface';
nw{VarName}.units = 'W/m^2';
nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'nlwrs';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'NLWRS_surface; NET DOWN SURFACE LW RAD FLUX';
nw{VarName}.units = 'W/m^2';
nw{VarName}.FillValue = '9.999e+20f' ; 

%VarName = 'tdsws';
%nw{VarName} = ncfloat('time', 'y', 'x');
%nw{VarName}.long_name = 'Total Precipitation Rate';
%nw{VarName}.units = 'W/m^2';
%nw{VarName}.FillValue = '9.999e+20f' ; 

%VarName = 'tdlws';
%nw{VarName} = ncfloat('time', 'y', 'x');
%nw{VarName}.long_name = 'TDWS_surface; DOWNWARD LW RAD FLUX; SURFACE';
%nw{VarName}.units = 'W/m^2';
%nw{VarName}.FillValue = '9.999e+20f' ; 

VarName = 'evaps';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'EVOS_surface; EVAP FROM OPEN SEA';
nw{VarName}.units = 'Kg/m^2/S';
nw{VarName}.FillValue = '9.999e+20f' ;

VarName = 'tprep';
nw{VarName} = ncfloat('time', 'y', 'x');
nw{VarName}.long_name = 'Total Precipitation Rate';
nw{VarName}.units = 'Kg/m^2/S';
nw{VarName}.FillValue = '9.999e+20f' ;

 
close(nw);
