function [year, month, AMO] = Func_0033_get_AMO(flags)


%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Volumes/kyy_raid/kimyy/Observation/AMO/amon.sm.long.data.txt
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2023/10/19 14:29:44

%% Initialize variables.
filename = '/Volumes/kyy_raid/kimyy/Observation/AMO/amon.sm.long.data.txt';
startRow = 2;
endRow = 169;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%5f%9f%9f%9f%9f%9f%9f%9f%9f%9f%9f%9f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
amon = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename startRow endRow formatSpec fileID dataArray ans;

amon(amon==-99.9900000000000)=NaN;
if flags ==1 % monthly
%     year=NPGOindex231019(:,1);
%     month=NPGOindex231019(:,2);
%     NPGO=NPGOindex231019(:,3);
elseif flags ==2 % yearly
    
    year = amon(:,1);
    AMO=mean(amon(:,2:13),2);
    month=0;
elseif flags ==3 % 3-year movmean
%     NPGO_yearly=reshape(NPGOindex231019(1:876,3), [876/12, 12]);
%     NPGO_yearly=mean(NPGO_yearly,2);
%     NPGO=movmean(NPGO_yearly,3);
%     year=movmean(1950:2022,3);
%     month=0;
else
    year=NaN;
    month=NaN;
    AMO=NaN;
%     plot(NPGO_yearly)
%     plot(NPGO_3ym)
    %1950:2022
%     plot(1960:2020,NPGO_3ym(11:71))
end

end
