function [year, month, NPGO] = Func_0032_get_NPGOices(ind_name, flags)

switch ind_name
    case 'NPGO'

        %% Import data from text file
            % Script for importing data from the following text file:
            %
            %    filename: /Volumes/kyy_raid/kimyy/Observation/NPGO/NPGO_index_231019.txt
            %
            % Auto-generated by MATLAB on 19-Oct-2023 13:53:46
            
            %% Set up the Import Options and import the data
            opts = delimitedTextImportOptions("NumVariables", 4);
            
            % Specify range and delimiter
            opts.DataLines = [36, 920];
            opts.Delimiter = ["  ", "\\"];
            
            % Specify column names and types
            opts.VariableNames = ["Var1", "deftab720", "VarName3", "VarName4"];
            opts.SelectedVariableNames = ["deftab720", "VarName3", "VarName4"];
            opts.VariableTypes = ["string", "double", "double", "double"];
            
            % Specify file level properties
            opts.ExtraColumnsRule = "ignore";
            opts.EmptyLineRule = "read";
            
            % Specify variable properties
            opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
            opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
            opts = setvaropts(opts, ["deftab720", "VarName3", "VarName4"], "ThousandsSeparator", ",");
            
            % Import the data
            NPGOindex231019 = readtable("/Volumes/kyy_raid/kimyy/Observation/NPGO/NPGO_index_231019.txt", opts);
            
            %% Convert to output type
            NPGOindex231019 = table2array(NPGOindex231019);
            
            %% Clear temporary variables
            clear opts
            
            NPGO = NPGOindex231019(1:876,:);
            NPGO(1:876/12,1:12)=reshape(NPGO(1:876,3), [876/12, 12]);
            year(1:876/12,1)=1950:2022;



    case 'AMO'
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/AMO/amon.sm.long.data.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 14:29:44
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/AMO/amon.sm.long.data.txt';
        startRow = 2;
        endRow = 169;
        
        %% Format for each line of text:
        %   column1: double (%f)
        %	column2: double (%f)
        %   column3: double (%f)
        %	column4: double (%f)
        %   column5: double (%f)
        %	column6: double (%f)
        %   column7: double (%f)
        %	column8: double (%f)
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        %	column12: double (%f)
        %   column13: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%5f%9f%9f%9f%9f%9f%9f%9f%9f%9f%9f%9f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        amon = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;
        
        amon(amon==-99.9900000000000)=NaN;
        year=amon(:,1);
        NPGO=amon(:,2:13);


    case 'PDO'

        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/PDO/PDO.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 15:08:12
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/PDO/PDO.txt';
        startRow = 12;
        
        %% Read columns of data as text:
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%4s%6s%6s%6s%6s%6s%6s%6s%6s%6s%6s%6s%s%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false);
        
        %% Close the text file.
        fclose(fileID);
        
        %% Convert the contents of columns containing numeric text to numbers.
        % Replace non-numeric text with NaN.
        raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
        for col=1:length(dataArray)-1
            raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
        end
        numericData = NaN(size(dataArray{1},1),size(dataArray,2));
        
        for col=[1,2,3,4,5,6,7,8,9,10,11,12,13]
            % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
            rawData = dataArray{col};
            for row=1:size(rawData, 1)
                % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
                regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
                try
                    result = regexp(rawData(row), regexstr, 'names');
                    numbers = result.numbers;
        
                    % Detected commas in non-thousand locations.
                    invalidThousandsSeparator = false;
                    if numbers.contains(',')
                        thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                        if isempty(regexp(numbers, thousandsRegExp, 'once'))
                            numbers = NaN;
                            invalidThousandsSeparator = true;
                        end
                    end
                    % Convert numeric text to numbers.
                    if ~invalidThousandsSeparator
                        numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                        numericData(row, col) = numbers{1};
                        raw{row, col} = numbers{1};
                    end
                catch
                    raw{row, col} = rawData{row};
                end
            end
        end
        
        
        %% Replace non-numeric cells with NaN
        R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
        raw(R) = {NaN}; % Replace non-numeric cells
        
        %% Create output variable
        PDO = cell2mat(raw);
        %% Clear temporary variables
        clearvars filename startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp R;
        
        PDO(PDO==-99.9900000000000)=NaN;
        NPGO=PDO(:,2:13);
        year=PDO(:,1);


    case 'IPO'
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/IPO/IPO_filtered.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 15:37:00
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/IPO/IPO_filtered.txt';
        startRow = 11;
        endRow = 180;
        
        %% Format for each line of text:
        %   column1: double (%f)
        %	column2: double (%f)
        %   column3: double (%f)
        %	column4: double (%f)
        %   column5: double (%f)
        %	column6: double (%f)
        %   column7: double (%f)
        %	column8: double (%f)
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        %	column12: double (%f)
        %   column13: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%4f%10f%10f%10f%10f%10f%10f%10f%10f%10f%10f%10f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        IPOfiltered = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;
        
        IPOfiltered(IPOfiltered==-99)=NaN;
        NPGO=IPOfiltered(:,2:13);
        year=IPOfiltered(:,1);

    case 'NAO'
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/NAO/NAO.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 15:50:59
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/NAO/NAO.txt';
        startRow = 12;
        endRow = 84;
        
        %% Format for each line of text:
        %   column1: double (%f)
        %	column2: double (%f)
        %   column3: double (%f)
        %	column4: double (%f)
        %   column5: double (%f)
        %	column6: double (%f)
        %   column7: double (%f)
        %	column8: double (%f)
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        %	column12: double (%f)
        %   column13: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%4f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        NAO = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;

        NPGO=NAO(:,2:13);
        year=NAO(:,1);

    case 'IOD' %DMI, dipole mode index
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/IOD/IOD_long.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 15:56:26
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/IOD/IOD_long.txt';
        startRow = 11;
        endRow = 163;
        
        %% Format for each line of text:
        %   column1: double (%f)
        %	column2: double (%f)
        %   column3: double (%f)
        %	column4: double (%f)
        %   column5: double (%f)
        %	column6: double (%f)
        %   column7: double (%f)
        %	column8: double (%f)
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        %	column12: double (%f)
        %   column13: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%4f%10f%10f%10f%10f%10f%10f%10f%10f%10f%10f%10f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        IODlong = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;

        NPGO=IODlong(:,2:13);
        year=IODlong(:,1);

    case 'ENSO'
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/ENSO/ENSO.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 16:43:11
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/ENSO/ENSO.txt';
        startRow = 11;
        endRow = 886;
        
        %% Format for each line of text:
        %   column2: double (%f)
        %	column3: double (%f)
        %   column4: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%*5s%5f%7f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        ENSO = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;
            
        NPGO = ENSO(1:size(ENSO,1),3);
        NPGO(1:size(ENSO,1)/12,1:12)=reshape(NPGO, [size(ENSO,1)/12, 12]);
        year=1950:2022;

    case 'AO'
        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    /Volumes/kyy_raid/kimyy/Observation/AO/AO.txt
        %
        % To extend the code to different selected data or a different text file, generate a function instead of a script.
        
        % Auto-generated by MATLAB on 2023/10/19 16:51:09
        
        %% Initialize variables.
        filename = '/Volumes/kyy_raid/kimyy/Observation/AO/AO.txt';
        startRow = 11;
        endRow = 83;
        
        %% Format for each line of text:
        %   column1: double (%f)
        %	column2: double (%f)
        %   column3: double (%f)
        %	column4: double (%f)
        %   column5: double (%f)
        %	column6: double (%f)
        %   column7: double (%f)
        %	column8: double (%f)
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        %	column12: double (%f)
        %   column13: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%4f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%f%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to the format.
        % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
        textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
        
        %% Create output variable
        AO = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename startRow endRow formatSpec fileID dataArray ans;

        NPGO=AO(:,2:13);
        year=AO(:,1);

    case 'SAM'
        fname='/Volumes/kyy_raid/kimyy/Observation/SAM/sam.nc';
        SAM=ncread(fname, 'SAM');
        time=ncread(fname, 'TSAXIS');
        time2=datevec(time+datenum(1900,1,1));
        year2=time2(:,1);
%         ncinfo(fname)
        SAM=SAM(1:528);
        year2=year2(1:528);
        NPGO2(1:size(SAM,1)/12,1:12)=reshape(SAM, [size(SAM,1)/12, 12]);
%         NPGO=NPGO';
        year2=min(year2):max(year2);
        year(1:29)=1950:1978;
        year(30:73)=year2;
        NPGO(1:29,1:12)=NaN;
        NPGO(30:73,1:12)=NPGO2;

%         year=year';
end


if flags == 1 % monthly
    NPGO=NPGO;
elseif flags ==2 % yearly
    NPGO=mean(NPGO,2);
    month=0;
elseif flags ==3 % 3-year movmean
    NPGO=mean(NPGO,2);
    NPGO=movmean(NPGO,3);
    year=movmean(year,3);
    month=0;
else
    year=NaN;
    month=NaN;
    NPGO=NaN;
%     plot(NPGO_yearly)
%     plot(NPGO_3ym)
    %1950:2022
%     plot(1960:2020,NPGO_3ym(11:71))
end



end